import datetime
from uuid import uuid4

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from shared.db.base import Base


class WorkPlan(Base):
    """A work plan generated by the Scout, approved before execution.

    Lifecycle: draft → approved → running → completed | failed | cancelled
    """

    __tablename__ = "work_plans"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default_factory=lambda: str(uuid4()), init=False
    )
    portal_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("portals.id", ondelete="CASCADE")
    )
    operation: Mapped[str] = mapped_column(String(20))  # venta | renta | vacacional
    status: Mapped[str] = mapped_column(String(20), default="draft")  # draft | approved | running | completed | failed | cancelled

    # Scout results
    total_listings: Mapped[int] = mapped_column(Integer, default=0)
    total_pages: Mapped[int] = mapped_column(Integer, default=0)
    states_count: Mapped[int] = mapped_column(Integer, default=0)
    anti_bot_level: Mapped[str] = mapped_column(String(10), default="none")
    selectors_healthy: Mapped[bool] = mapped_column(Boolean, default=True)
    scout_report: Mapped[dict | None] = mapped_column(JSONB, default=None)  # full ScoutReport.to_dict()

    # Plan configuration
    num_workers: Mapped[int] = mapped_column(Integer, default=1)
    visit_detail: Mapped[bool] = mapped_column(Boolean, default=True)
    worker_assignments: Mapped[list | None] = mapped_column(JSONB, default=None)  # [{worker_id, states, total_listings}]
    proxy_provider: Mapped[str | None] = mapped_column(String(30), default=None)

    # Estimates
    estimated_hours: Mapped[float] = mapped_column(Float, default=0.0)
    estimated_cost_usd: Mapped[float] = mapped_column(Float, default=0.0)

    # Execution results
    actual_hours: Mapped[float | None] = mapped_column(Float, default=None)
    actual_cost_usd: Mapped[float | None] = mapped_column(Float, default=None)
    total_scraped: Mapped[int] = mapped_column(Integer, default=0)
    total_new: Mapped[int] = mapped_column(Integer, default=0)
    total_errors: Mapped[int] = mapped_column(Integer, default=0)
    error_detail: Mapped[str | None] = mapped_column(Text, default=None)

    # Timestamps
    approved_at: Mapped[datetime.datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    started_at: Mapped[datetime.datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    finished_at: Mapped[datetime.datetime | None] = mapped_column(DateTime(timezone=True), default=None)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), init=False
    )
